on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.tf'

jobs:
  tf_pr_develop:
    name: develop - terraform plan
    runs-on: ubuntu-latest
    steps:
      - name: Add some context
        env: 
          BASE_REF: ${{ github.base_ref }}
          IS_MERGED: ${{ github.event.pull_request.merged }}
          GH_ACTION: ${{ github.event.action }}
        run: |
          echo github.base_ref: "$BASE_REF"
          echo github.event.pull_request.merged: "$IS_MERGED"
          echo github.event.action: "$GH_ACTION"