name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been merged

  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - '**.tf'
#   pull_request:
#     branches:
#       - main
#     paths:
#       - '**.tf'

# jobs:
#   just_testing:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo github.event.number: ${{ github.event.number }}
          
#       - run: |
#           echo github.event_name: ${{ github.event_name }}

#       - run: |
#           echo github.event.pull_request: ${{ github.event.pull_request }}
      
#       - run: |
#           echo github.event.pull_request.merged: ${{ github.event.pull_request.merged }}
      
#       - run: |
#           echo github.event.pull_request.closed_at: ${{ github.event.pull_request.closed_at }}

#       - run: |
#           echo github.ref: ${{ github.ref }}

#       - env:
#           GITHUB_CONTEXT: ${{ toJSON(github) }}
#         run: echo "$GITHUB_CONTEXT"
