on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  just_testing:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo github.event.number: ${{ github.event.number }}
          
      - run: |
          echo github.event_name: ${{ github.event_name }}

      - run: |
          echo github.event.pull_request: ${{ github.event.pull_request }}
      
      - run: |
          echo github.event.pull_request.merged: ${{ github.event.pull_request.merged }}

      - run: |
          echo github.ref: ${{ github.ref }}
